# - name: applying conditions 
#   hosts: all
#   become: true
#   tasks:
#     - name: install httpd
#       yum: 
#         name: httpd
#         state: latest
#       when: ansible_os_family=="RedHat"

#     - name: install apache2
#       apt: 
#         name: apache2
#         state: latest
#       when: ansible_os_family=="Debian"

- name: Applying conditions
  hosts: all
  become: true
  tasks:
    - name: Install httpd on RedHat-based systems
      yum:
        name: httpd
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install apache2 on Debian-based systems
      apt:
        name: apache2
        state: latest
      when: ansible_os_family == "Debian"
