- name: This task include global andn local variable   
  hosts: all
  vars: 
    global_var: "Students"
    tasks: 
      - name: using global variable
        debug: 
          msg: "Hello {{ global_var }} , welcome to learning ansible."
      - name: using local variable
        debug: 
          msg: "Hello {{ local_var }} , welocme to learning ansible."
          vars: 
          local_var: "Vaishnavi"