# - name: install apache2
#   package:
#     name: "{{package}}"
#     state: latest
# - name: copy index.html file
#   copy:
#     src: ./index.html
#     dest: /var/www/html/index.html
#   notify:
#       - restart service
  
- name: install apache2
  package:
    name: "{{ package }}"
    state: latest

- name: copy index.html file
  copy:
    src: ./index.html
    dest: /var/www/html/index.html
  notify:
    - restart apache2

- name: start apache2 service
  service:
    name: apache2
    state: started
    enabled: yes


